name: Packager

on:
  create:
#    paths-ignore:
#      - '.github/**'
#  push:
#    branches:
#      - master
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]'
#    paths-ignore:
#      - '.github/**'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v2

      - name: Package Retail
        uses: BigWigsMods/packager@master
        with:
          args: -g retail -m .pkgmeta

      - name: Package Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic -m .pkgmeta
